on: [push]

jobs:
  import_to_design_center:
    runs-on: ubuntu-latest
    name: A job to import a specification to design center
    steps:
      - name: Import Specification
        id: import_specification
        uses: aalami-muley/import-api-spec-to-design-center-action@main
        with:
          ORGANIZATION_ID: 'f60b1434-1059-4f0f-a28c-ccf4a9be05b2'
          USER_ID: '612cf2dd-9f92-4a08-97ed-f6be4faf06ca'
          BRANCH: 'master'
          CLASSIFIER: 'raml'
          PROJECT_NAME: 'Import Specification Action DEMO'
          PROJECT_DIRECTORY: '${{ github.workspace }}/test'
          SPEC_PATH: 'import-specification-action-demo.raml'
          TOKEN: 'f2a2bedc-3342-43bd-877c-716a3e33f801'